@baseUrl = http://localhost:3000

### Get Table
GET {{baseUrl}}/imc/table HTTP/1.1

### Calculate IMC - current
POST {{baseUrl}}/imc/calculate HTTP/1.1
Content-Type: application/json

{
  "weight": 90,
  "height": 1.77
}

### Calculate IMC - v1
POST {{baseUrl}}/v1/imc/calculate HTTP/1.1
Content-Type: application/json

{
  "weight": 90,
  "height": 1.77
}


### Calculate IMC v2
POST {{baseUrl}}/v2/imc/calculate HTTP/1.1
Content-Type: application/json

{
  "weight": 90,
  "height": 1.77
}